### ISSUE TITLE
feature: adjust output directory

### ISSUE THREAD

**Issue by BenPortner** [brightway-lca/mrio_common_metadata#2]
For me, the output ended up in the conda environment under:
C:\USER\miniconda\envs\ENV_NAME\Lib\site-packages\mrio_common_metadata-0.1.1-py3.8.egg\mrio_common_metadata\conversion\exiobase_3_hybrid_io\data

I think it would be better to let the user specify a directory or put the output in a folder in the input directory.

**Comment by cmutel** [comment]
Closed in 6925d6523f75f3fc30f2223267479892747689d0.
